# Generated by Django 5.1.3 on 2024-11-07 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('C1', 'UCI C1'), ('C2', 'UCI C2'), ('NC', 'National Championship'), ('CDM', 'Coupe du Monde')], default='C2', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('rating', models.FloatField(default=800)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='H', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('previous_rating', models.FloatField()),
                ('new_rating', models.FloatField()),
                ('race_category', models.CharField(default='', max_length=200)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='eloapp.race')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='eloapp.rider')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('race', 'rider')},
            },
        ),
    ]
