# Generated by Django 5.1.3 on 2024-11-07 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eloapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='raceresult',
            unique_together=set(),
        ),
    ]
