# Generated by Django 5.1.3 on 2024-11-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eloapp', '0002_alter_raceresult_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='sex',
        ),
        migrations.AddField(
            model_name='rider',
            name='ratingtype',
            field=models.CharField(default='Men Elite', max_length=50),
        ),
    ]
