# Generated by Django 5.1.3 on 2024-11-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eloapp', '0003_remove_rider_sex_rider_ratingtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='current_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='position_change',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='rating_change',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
